import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/home/Navbar";
import { ThemeProvider } from "@/components/theme/theme-provider";
// import "./map.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-screen overflow-hidden block md:hidden relative">
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Navbar />
            {children}
          </ThemeProvider>
        </div>
        <div className="hidden md:flex justify-center items-center h-screen w-screen overflow-hidden">
          <h1 className="text-muted-foreground text-xs">
            Currently this web app supports mobile view, you can switch to
            mobile view to access this application
          </h1>
        </div>
      </body>
    </html>
  );
}
